version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/test_q/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0
      - CELERY_BROCKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - migration
      - pg_db
      - redis
  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/usr/src/test_q/
    depends_on:
      - pg_db
  celery:
    build: .
    command: celery -A test_q worker -l INFO
    volumes:
      - .:/usr/src/test_q/
    depends_on:
      - django
      - redis
  pg_db:
    image: postgres:10.1-alpine
    container_name: pg_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    image: redis:alpine
volumes:
  pgdata:
