# Generated by Django 4.0.6 on 2022-07-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.IntegerField(unique=True, verbose_name='Номер заказа')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Сумма в долларах')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Сумма в рублях')),
                ('delivery_time', models.DateField(verbose_name='Срок поставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
