# Generated by Django 4.0.6 on 2022-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='article',
            field=models.CharField(max_length=255, unique=True, verbose_name='Номер заказа'),
        ),
    ]
