# Generated by Django 4.0.6 on 2022-07-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_massage',
            field=models.BooleanField(default=False, verbose_name='Оповещение о итечение срока'),
        ),
    ]
