# Generated by Django 4.0.6 on 2022-07-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_delivery_massage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Курс доллара')),
            ],
            options={
                'verbose_name': 'Курс доллара',
                'verbose_name_plural': 'Курс доллара',
            },
        ),
    ]
